"""
api.py — FastAPI Backend
Spotify Popularity Predictor
Author: Amila Herenda

Start with:
    uvicorn app.api:app --reload --port 8000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:8000/docs
"""

# =============================================================================
# IMPORTS
# =============================================================================
import os
from contextlib import asynccontextmanager

import joblib
import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

# =============================================================================
# PATHS
# =============================================================================
# Resolve paths relative to the project root, not this file's location.
# When running `uvicorn app.api:app` from the project root, os.getcwd()
# returns the project root, so "models/classifier.pkl" resolves correctly.
CLF_PATH = os.path.join("models", "classifier.pkl")
REG_PATH = os.path.join("models", "regressor.pkl")


# =============================================================================
# STARTUP — load models once, reuse for every request
# =============================================================================
# WHY use a lifespan context manager?
# We want the models to be loaded ONCE when the server starts, not on every
# HTTP request. Loading a .pkl file from disk on every request would be very
# slow (100–500 ms per load). With lifespan, they load once and live in memory
# for the entire lifetime of the server process.
#
# The `models` dict is the shared in-memory store for the two pipelines.
models: dict = {}


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Load models on startup; clean up on shutdown."""
    # ── Startup ──────────────────────────────────────────────────────────────
    for path, key in [(CLF_PATH, "classifier"), (REG_PATH, "regressor")]:
        if not os.path.exists(path):
            raise RuntimeError(
                f"Model file not found: {path}\n"
                "Run  python train.py  first to generate the .pkl files."
            )
        models[key] = joblib.load(path)
        print(f"[startup] Loaded {key} from {path}")

    yield   # ← server is running here; all requests are handled between yield points

    # ── Shutdown ─────────────────────────────────────────────────────────────
    models.clear()
    print("[shutdown] Models unloaded.")


# =============================================================================
# APP INSTANCE
# =============================================================================
app = FastAPI(
    title="Spotify Popularity Predictor API",
    description=(
        "Predicts whether a song will be popular (classification) "
        "and its exact popularity score (regression) from audio features."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# =============================================================================
# CORS — allow Streamlit (different port) to call this API
# =============================================================================
# WHY CORS?
# Browsers block HTTP requests from one origin (e.g. localhost:8501 — Streamlit)
# to another origin (localhost:8000 — this API) unless the server explicitly
# allows it. This is the browser's Same-Origin Policy security feature.
# CORSMiddleware adds the required `Access-Control-Allow-Origin` headers so
# Streamlit's fetch calls are allowed through.
#
# allow_origins=["*"] is fine for a student project / development.
# In production you would restrict this to your Streamlit domain only.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],        # allow all origins (Streamlit Cloud, localhost, etc.)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# =============================================================================
# PYDANTIC SCHEMAS
# =============================================================================
# WHY Pydantic?
# FastAPI uses Pydantic models to:
#   1. Validate incoming JSON (wrong type → 422 error automatically)
#   2. Generate interactive docs at /docs (try-it-out UI)
#   3. Provide type safety — we know every field is the right type inside the handler
#
# Field(...) means the field is required (no default).
# ge / le enforce numeric bounds so users can't send nonsense values.
# description shows up in the /docs UI — very useful for demos.


class AudioFeatures(BaseModel):
    """Raw audio features exactly as they appear in the Spotify dataset."""

    # ── Core audio properties ─────────────────────────────────────────────────
    danceability: float = Field(
        ..., ge=0.0, le=1.0,
        description="How suitable a track is for dancing (0 = least, 1 = most)",
        example=0.73,
    )
    energy: float = Field(
        ..., ge=0.0, le=1.0,
        description="Perceptual measure of intensity and activity",
        example=0.65,
    )
    loudness: float = Field(
        ..., ge=-60.0, le=5.0,
        description="Overall loudness in decibels (dB). Typical range: -60 to 0",
        example=-6.5,
    )
    speechiness: float = Field(
        ..., ge=0.0, le=1.0,
        description="Presence of spoken words (>0.66 = spoken, <0.33 = music)",
        example=0.05,
    )
    acousticness: float = Field(
        ..., ge=0.0, le=1.0,
        description="Confidence that the track is acoustic (1.0 = high confidence)",
        example=0.12,
    )
    instrumentalness: float = Field(
        ..., ge=0.0, le=1.0,
        description="Predicts whether a track contains no vocals",
        example=0.0,
    )
    liveness: float = Field(
        ..., ge=0.0, le=1.0,
        description="Detects presence of an audience (>0.8 = likely live)",
        example=0.09,
    )
    valence: float = Field(
        ..., ge=0.0, le=1.0,
        description="Musical positiveness (1 = happy/euphoric, 0 = sad/angry)",
        example=0.55,
    )
    tempo: float = Field(
        ..., ge=30.0, le=300.0,
        description="Estimated tempo in beats per minute (BPM)",
        example=120.0,
    )

    # ── Structural properties ─────────────────────────────────────────────────
    key: int = Field(
        ..., ge=0, le=11,
        description="Musical key (0=C, 1=C#, 2=D, … 11=B). -1 if not detected.",
        example=5,
    )
    mode: int = Field(
        ..., ge=0, le=1,
        description="Modality: 1 = major, 0 = minor",
        example=1,
    )
    time_signature: int = Field(
        ..., ge=3, le=7,
        description="Estimated time signature (3 to 7 beats per bar)",
        example=4,
    )
    duration_ms: int = Field(
        ..., ge=1000, le=3_600_000,
        description="Track duration in milliseconds",
        example=210_000,
    )
    explicit: int = Field(
        ..., ge=0, le=1,
        description="1 = contains explicit content, 0 = clean",
        example=0,
    )

    # ── Genre ─────────────────────────────────────────────────────────────────
    track_genre: str = Field(
        ...,
        description="Genre label (e.g. 'pop', 'rock', 'hip-hop'). "
                    "Unknown genres are handled gracefully.",
        example="pop",
    )


class PredictionResponse(BaseModel):
    """Shape of the JSON the API returns."""

    popular: bool = Field(description="True if predicted popularity >= 70")
    popularity_score: float = Field(description="Predicted popularity score (0–100)")
    confidence: float = Field(
        description="Model confidence: probability the song IS popular (0–1)"
    )
    label: str = Field(description="Human-readable verdict")


# =============================================================================
# FEATURE ENGINEERING  (mirrors train.py — MUST stay in sync)
# =============================================================================
def _engineer_features(raw: dict) -> pd.DataFrame:
    """
    Apply the same feature engineering as train.py's engineer_features().
    Returns a one-row DataFrame ready to pass into pipeline.predict().

    WHY replicate this here?
    The scikit-learn Pipeline contains the preprocessor (scaler + encoder)
    but NOT the feature engineering step. Feature engineering in train.py
    happened on the full DataFrame BEFORE the pipeline was fitted. So we
    must apply the same transformations here before calling pipeline.predict().

    If you ever change engineer_features() in train.py, update this function
    too AND retrain the model — otherwise the column layout will mismatch.
    """
    df = pd.DataFrame([raw])    # one-row DataFrame

    # Engineered features — identical formulas to train.py
    df["energy_acoustic_ratio"] = df["energy"] / (df["acousticness"] + 1e-6)
    df["dance_energy"]          = df["danceability"] * df["energy"]
    df["valence_energy"]        = df["valence"] * df["energy"]
    df["tempo_beat_ratio"]      = df["tempo"] / df["time_signature"].clip(lower=1)
    df["duration_min"]          = df["duration_ms"] / 60_000

    return df


# =============================================================================
# ENDPOINTS
# =============================================================================

@app.get("/health", summary="Health check")
def health() -> dict:
    """
    Returns 200 OK if the API is running and both models are loaded.
    Streamlit calls this on startup to verify the backend is alive.
    """
    return {
        "status": "ok",
        "models_loaded": list(models.keys()),
    }


@app.post("/predict", response_model=PredictionResponse, summary="Predict popularity")
def predict(features: AudioFeatures) -> PredictionResponse:
    """
    Accepts audio features and returns:
    - `popular`          — True / False
    - `popularity_score` — predicted score 0–100
    - `confidence`       — probability of being popular (0–1)
    - `label`            — human-readable string

    The endpoint loads NO models — they were loaded once at startup.
    """
    # ── Guard: models must be loaded ─────────────────────────────────────────
    if "classifier" not in models or "regressor" not in models:
        raise HTTPException(
            status_code=503,
            detail="Models not loaded. The server may still be starting up.",
        )

    # ── Build feature DataFrame (one row) ────────────────────────────────────
    raw = features.model_dump()         # Pydantic → plain Python dict
    X = _engineer_features(raw)         # add engineered columns

    # ── Classification ────────────────────────────────────────────────────────
    clf = models["classifier"]
    popular_flag  = bool(clf.predict(X)[0])
    # predict_proba returns [[prob_class_0, prob_class_1]]
    confidence    = float(clf.predict_proba(X)[0][1])

    # ── Regression ────────────────────────────────────────────────────────────
    reg = models["regressor"]
    score_raw     = float(reg.predict(X)[0])
    # Clamp to valid range — regression can occasionally predict outside 0–100
    score         = float(np.clip(score_raw, 0.0, 100.0))

    # ── Compose human-readable label ─────────────────────────────────────────
    if popular_flag:
        label = f"Popular  (predicted score: {score:.1f} / 100)"
    else:
        label = f"Not popular  (predicted score: {score:.1f} / 100)"

    return PredictionResponse(
        popular=popular_flag,
        popularity_score=round(score, 2),
        confidence=round(confidence, 4),
        label=label,
    )


# =============================================================================
# ALLOW RUNNING DIRECTLY  (python app/api.py)
# =============================================================================
if __name__ == "__main__":
    import uvicorn
    uvicorn.run("app.api:app", host="0.0.0.0", port=8000, reload=True)
